### ISSUE TITLE
FTP Not supported?

### ISSUE THREAD

**Issue by moataz-moussa** [OpusCapita/filemanager#286] opened 2020-07-08 21:36 UTC
Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01
Original Estimation | ???h
Remaining Estimation | ???h

**Comment by achernyakevich-sc** [comment] 2021-04-28 16:11
@moataz-moussa 
You question could be answered by pointing to #123 - at the moment connector for FTP/sFTP is not implemented in scope of this repository. If anybody would contribute and implement it could be formed as pull request and shared further for community.

If you are ready to spend some money for it you could contact to me directly in private and we could discuss details.

**Comment by achernyakevich-sc** [comment] 2021-04-28 16:12
Duplicate of #123.

**Closed** 2021-04-28 16:12 UTC

**Comment by achernyakevich-sc** [comment] 2021-04-28 16:14
@moataz-moussa
BTW: You could add 👍 to #123. If it will collect enough then it could be treated as higher priority and it will increase a chance to be implemented soon.
