### ISSUE TITLE
Dark Mode option missing

### ISSUE THREAD

**Issue by imdkbj** [OpusCapita/filemanager#318] opened 2021-07-08 13:48 UTC
Not found any option for dark mode.

**Comment by visortelle** [comment] 2021-07-08 17:40
It's another filemanager. :)

**Comment by imdkbj** [comment] 2021-07-08 17:44
Sorry ! Link removed and comment updated

**Comment by visortelle** [comment] 2021-07-08 17:51
You can always override styles as you wish and make a PR.

Example: https://github.com/OpusCapita/filemanager/blob/master/packages/client-react/src/client/components/themes/ex-jcatalog.less

**Comment by achernyakevich-sc** [comment] 2021-07-11 09:12
Short summary before closing the issue:
- filemanager by default provides "white" theme (CSS/images).
- from other side filemanager does not limit any developer to created customized theme.
- as soon as anybody will create "dark" theme and create pull-requst (or provide it in some other way) it will be checked to be included to default package).

This issue is closed as this is not a bug. If it will be required we could create and issue to add customized "dark" theme.

**Closed by achernyakevich-sc** 2021-07-11 09:12 UTC
